name: buzz_logger
description: A logger service and model(s)
version: 0.0.2
homepage: https://github.com/abbas-alshafai/buzz_utils

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  logger: ^1.1.0
  copy_with_extension: ^4.0.0
  buzz_utils: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  copy_with_extension_gen: ^4.0.0
  build_runner: ^2.1.7


flutter: