name: buzz_logger
description: A logger service and model(s)
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  logger:
  copy_with_extension_gen:

  buzz_utils:
    git:
      ref: master
      url: https://github.com/abbas-alshafai/buzz_utils

#  buzz_result:
#    git:
#      ref: master
#      url: https://github.com/abbas-alshafai/buzz_result

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  copy_with_extension_gen: ^4.0.0
  build_runner: ^2.1.7


flutter:
